#!/usr/bin/python3
# Package manager for python3 binaries compiled to ELF
import argparse
import os
import random
import string

def get_random_string(length):
    letters = string.ascii_lowercase
    result_str = ''.join(random.choice(letters) for i in range(length))
    return result_str 

def prepend(file, line):
    temp_file='/tmp/pypacktemp-'+get_random_string(20)
    temp_f=open(temp_file,'w')
    temp_f.write(line+'\n')
    with open(file,'r') as f:
        for l in f.readlines:
            temp_f.write(l)
    temp_f.close()
    os.system(f'mv {temp_file} {file}')
pypack_dir='/etc/pypack/'

if os.geteuid() != 0:
    exit("You need to have root privileges to run this script.\nPlease try again, this time using 'sudo'. Exiting.")

parser=argparse.ArgumentParser()
parser.add_argument('-i', help='specify name of the package to install (e.g. pypack -i foo -f bar.py will install bar.py and it will be installed in /usr/bin/foo)')
parser.add_argument('-f', help='specify the python3 package to install')
parser.add_argument('-p', '--purge', help='uninstall specified package')
parser.add_argument('-n', '--no-compile', help='if --no-compile is specified, the script will be installed without being compiled',action='count')
args=parser.parse_args()

if args.i and not bool(args.no_compile):
    out_file=args.i
    in_file=args.f
    if os.path.isfile(f'/usr/bin/{out_file}'):                      # if file exists: exit with error
        exit('[error] /usr/bin/{out_file} exists!')
    os.system(f'cython3 {in_file} -o /tmp/{out_file}_temp.c --embed')
    os.system(f'gcc -Os -I /usr/include/python3.8  /tmp/{out_file}_temp.c -o /tmp/{out_file}_pypack.PYPACK -lpython3.8 -lpthread -lm -lutil -ldl')
    os.system(f'rm /tmp/{out_file}_temp.c')
    os.system(f'chmod +x /tmp/{out_file}_pypack.PYPACK && sudo cp /tmp/{out_file}_pypack.PYPACK /usr/bin')

if args.i and bool(args.no_compile):
    out_file=args.i
    in_file=args.f
    with open(in_file,'r') as f:
        line1=f.readline()
        if '#!/usr/bin/python' in line1:
            #thats cool
            print(f'{line1} in 1st line. that\'s cool!')
        else:
            #thats not cool
            need2change=1
    if need2change:
        #Lets suppose we use python3
        prepend(in_file,'#!/usr/bin/python3')
        #if in_file[-3:] == '.py':
        #    extention=1
    if os.path.isfile(f'/usr/bin/{out_file}'):                      # if file exists: exit with error
        exit('[error] /usr/bin/{out_file} exists!')
    os.system(f'chmod +x {in_file} && cp {in_file} /usr/bin/{out_file}')
if args.purge:
    pass

